# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Data/Labs/SchemaTech/lab4/lab4.cache/wt [current_project]
set_property parent.project_path C:/Data/Labs/SchemaTech/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Data/Labs/SchemaTech/lab4/lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Data/Labs/SchemaTech/schoolRISCV/src/sr_cpu.vh
read_verilog -library xil_defaultlib {
  C:/Data/Labs/SchemaTech/schoolRISCV/src/adder.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/func.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/mult.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/shift.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/sm_hex_display.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/sm_register.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/sm_rom.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/sm_top.v
  C:/Data/Labs/SchemaTech/schoolRISCV/src/sr_cpu.v
  C:/Data/Labs/SchemaTech/schoolRISCV/board/de0_cv/de0_cv.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top de0_cv -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef de0_cv.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file de0_cv_utilization_synth.rpt -pb de0_cv_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
